### ISSUE TITLE
findOverSide在四周侵占的情况下，找不准数字中心的问题

### ISSUE THREAD

**Issue by Skypow2012** [Skypow2012/img-tool#3]
在四方数字图片有超出格子时，会导致找到的数字没有居中，识别就不准。
（现在使用的方法是直接找存在黑点的横轴、竖轴，优化成找手写线条整体，就可以解决这个问题）
例子：下图的腰围第二个数字因为上面的7的一竖超到了下面，导致1的中心被判定在左边了，整体就靠右了，最后这个1就被识别成了7。
![test17](https://user-images.githubusercontent.com/18132118/75303364-81324b00-587b-11ea-9835-586d630aae2e.jpg)
![Snipaste_2020-02-26_09-40-33](https://user-images.githubusercontent.com/18132118/75303612-2a794100-587c-11ea-86b1-f14afa699dac.png)
![Snipaste_2020-02-26_09-41-05](https://user-images.githubusercontent.com/18132118/75303615-2c430480-587c-11ea-929e-2dc334446884.png)

**Comment by flowkscai** [comment]
转黑底白字后，可以通过膨胀，找轮廓，截取最大轮廓所在区域的手写数字，然后居中到28x28的背景图中
